CREATE TABLE PRODUCER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE STUDIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE NOMINEE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    WINNER BOOLEAN NOT NULL,
    YEAR INT NOT NULL
);

CREATE TABLE NOMINEE_STUDIO (
    NOMINEE_ID BIGINT NOT NULL,
    STUDIO_ID BIGINT NOT NULL  
);

CREATE TABLE NOMINEE_PRODUCER (
    NOMINEE_ID BIGINT NOT NULL,
    PRODUCER_ID BIGINT NOT NULL  
);

ALTER TABLE NOMINEE_PRODUCER ADD CONSTRAINT FK_NOMINEEPRODUCER_PRODUCER FOREIGN KEY (PRODUCER_ID) REFERENCES PRODUCER;
ALTER TABLE NOMINEE_PRODUCER ADD CONSTRAINT FK_NOMINEEPRODUCER_NOMINEE FOREIGN KEY (NOMINEE_ID) REFERENCES NOMINEE;

ALTER TABLE NOMINEE_STUDIO ADD CONSTRAINT FK_NOMINEESTUDIO_STUDIO FOREIGN KEY (STUDIO_ID) REFERENCES STUDIO;
ALTER TABLE NOMINEE_STUDIO ADD CONSTRAINT FK_NOMINEESTUDIO_NOMINEE FOREIGN KEY (NOMINEE_ID) REFERENCES NOMINEE;